# Generated by Django 3.1.2 on 2022-06-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='person',
            name='my_contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_contact_id', to='api.contact'),
        ),
    ]
