# Generated by Django 3.1.2 on 2022-06-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220629_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='my_contact_id',
            new_name='contact_id',
        ),
    ]
