# Generated by Django 3.1.2 on 2022-06-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220629_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id',
            new_name='cid',
        ),
    ]
