# Generated by Django 3.1.2 on 2022-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220629_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='api.Contact'),
        ),
    ]
